/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonfight;

import Types.DragonMaker;
import Types.FireDragonMaker;
import Types.IceDragonMaker;
import Types.ThunderDragonMaker;

/**
 *
 * @author DELL
 */
public class CreateDragonScreen extends javax.swing.JFrame {

    DragonMaker dragonMaker;
    
    public CreateDragonScreen() {
        initComponents();
        dragonMaker = null;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firebtn = new javax.swing.JButton();
        icebtn = new javax.swing.JButton();
        thunderbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("SELECT A DRAGON MAKER");

        firebtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.warning.borderColor"));
        firebtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        firebtn.setForeground(new java.awt.Color(153, 0, 0));
        firebtn.setText("FIRE");
        firebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firebtnActionPerformed(evt);
            }
        });

        icebtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.warning.borderColor"));
        icebtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        icebtn.setForeground(new java.awt.Color(51, 178, 246));
        icebtn.setText("ICE");
        icebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icebtnActionPerformed(evt);
            }
        });

        thunderbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.warning.borderColor"));
        thunderbtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        thunderbtn.setForeground(new java.awt.Color(51, 0, 102));
        thunderbtn.setText("THUNDER");
        thunderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thunderbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icebtn)
                    .addComponent(firebtn)
                    .addComponent(thunderbtn))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firebtn, icebtn, thunderbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(firebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thunderbtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firebtnActionPerformed
            dragonMaker = new FireDragonMaker();
            this.setVisible(false);
             SelectTypeScreen typeScreen = new SelectTypeScreen(dragonMaker);
             typeScreen.setVisible(true);
           
              
    }//GEN-LAST:event_firebtnActionPerformed

    private void icebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icebtnActionPerformed
          dragonMaker = new IceDragonMaker();
         this.setVisible(false);
         SelectTypeScreen typeScreen = new SelectTypeScreen(dragonMaker);
         typeScreen.setVisible(true);
        
    }//GEN-LAST:event_icebtnActionPerformed

    private void thunderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thunderbtnActionPerformed
        dragonMaker = new ThunderDragonMaker();  
        this.setVisible(false);
             SelectTypeScreen typeScreen = new SelectTypeScreen(dragonMaker);
             typeScreen.setVisible(true);
              
    }//GEN-LAST:event_thunderbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDragonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDragonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDragonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDragonScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CreateDragonScreen().setVisible(true);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firebtn;
    private javax.swing.JButton icebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton thunderbtn;
    // End of variables declaration//GEN-END:variables
}
