/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dragonfight;

import Hero.Armor;
import Hero.GoldArmor;
import Hero.Hero;
import Hero.ShinyArmor;
import Hero.hammer;
import Hero.sword;
import Hero.weapon;
import Types.Dragon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class SelectHeroScreen extends javax.swing.JFrame {

    /**
     * Creates new form SelectHeroScreen
     */
    weapon weapon;
    Armor armor;
    Dragon dragon;
    Hero hero;
    public SelectHeroScreen(Dragon dragon) 
    { 
        initComponents();
        this.dragon = dragon;
         }
   
    
    public boolean createhero()
    {
        
       String heroname = nametxt.getText();
      
    
       if(selectWeapon() && selectArmor())
       {
          hero = new Hero(heroname,weapon,armor);
          hero.setName(heroname);
          hero.setArmor(armor);
          hero.setWeapon(weapon);
         return true;
       }
        
       else
       {
           return false;
       }
    
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        swordbx = new javax.swing.JCheckBox();
        hammerbx = new javax.swing.JCheckBox();
        goldbx = new javax.swing.JCheckBox();
        shinybx = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CREATE YOUR HERO");

        jLabel2.setText("NAME:");

        jLabel3.setText("WEAPON:");

        jLabel4.setText("ARMOR:");

        swordbx.setText("sword");

        hammerbx.setText("hammer");

        goldbx.setText("gold");

        shinybx.setText("shiny");

        jButton1.setText("next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(swordbx, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goldbx, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hammerbx, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shinybx, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(swordbx)
                    .addComponent(hammerbx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(goldbx)
                    .addComponent(shinybx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(createhero())
        {
           this.dispose();
          PreFightPanel pfp = new PreFightPanel(dragon,hero);
           pfp.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox goldbx;
    private javax.swing.JCheckBox hammerbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nametxt;
    private javax.swing.JCheckBox shinybx;
    private javax.swing.JCheckBox swordbx;
    // End of variables declaration//GEN-END:variables

    private boolean selectWeapon() {
       
        
        if(swordbx.isSelected() && (!hammerbx.isSelected()) )
       {
           weapon = new sword();
           weapon.CreateWeapon();
           return true;
            
       }
       else if(hammerbx.isSelected() && (!swordbx.isSelected()))
       {
           weapon = new hammer();
           weapon.CreateWeapon();
           return true;
       }
       else
       {
            JOptionPane.showMessageDialog(this,"your weapon choose is incorrect");
           return false;
       }
       
        
    }

    private boolean selectArmor() 
    {
        if(goldbx.isSelected() && (!shinybx.isSelected()))
       {
           armor = new GoldArmor();
           armor.createArmor();
           return true;
           
       }
       else if(shinybx.isSelected() && (!goldbx.isSelected()))
       {
           armor = new ShinyArmor();
           armor.createArmor();
           return true;
       }
        else
       {
            JOptionPane.showMessageDialog(this,"your armor choose is incorrect");
             return false;
       }
       
    }
}
